# them con https://www.zabbix.com/documentation/current/en/manual/installation/containers
# 
version: '3.3'

services:
  mysql-db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      #      MYSQL_DATABASE: auth
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
    restart: on-failure
  redis:
    image: redis:7.2.1-alpine3.18
    environment:
      REDIS_PASSWORD: Redis@123
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: on-failure
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
      image: grafana/grafana:9.5.2
      container_name: grafana
      ports:
        - "3000:3000"
      restart: unless-stopped
      volumes:
        - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
volumes:
  grafana:
    driver: local
  mysql-db:
    driver: local
  redis-data:
    driver: local
